export const AppConfig = {
  API_URL: process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8888/api',
  GOOGLE_OAUTH_CLIENT_ID: process.env.GOOGLE_OAUTH_CLIENT_ID || 'OUATH_CLIENT_ID',
  GOOGLE_OAUTH_CLIENT_SECRET: process.env.GOOGLE_OAUTH_CLIENT_SECRET || 'OAUTH_CLIENT_SECRET',
  GOOGLE_OAUTH_REDIRECT: process.env.GOOGLE_OAUTH_REDIRECT || 'OAUTH_REDIRECT_URL',
};
